# Generated by Django 5.1.7 on 2025-03-31 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rolsa', '0002_booking_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='product',
            field=models.CharField(choices=[('solar_panel', 'Solar Panel'), ('heat_pump', 'Heat Pump'), ('solar_farm', 'Solar Farm'), ('home_energy_solutions', 'Home Energy Solutions'), ('windmill', 'Windmill'), ('electric_charging_system', 'Electric Charging System')], default='pending', max_length=30),
        ),
    ]
